todo:
	g++ -c -o JugadorMax.o JugadorMax.cpp
	g++ -c -o JugadorMin.o JugadorMin.cpp
	g++ -c -o NodoDeJuego.o NodoDeJuego.cpp
	g++ -c -o Partida.o Partida.cpp
	g++ -c -o Tablero.o Tablero.cpp
	g++ -c -o main.o main.cpp
	g++ -o tictacmaximin main.o JugadorMax.o JugadorMin.o NodoDeJuego.o Partida.o Tablero.o